name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - deployment-branch 

jobs:
  deploy:
    runs-on: self-hosted  # This tells it to run on YOUR Pi, not GitHub's cloud
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Virtual Env and Install Dependencies
        run: |
          uv sync
          source ./venv/bin/activate
          
      - name: Test Run (Optional)
        run: |
          source ./venv/bin/activate
          # Just printing version or help to ensure env is healthy
          python3 --version
      
      - name: Notify
        run: echo "Deployment to Pi 5 Complete!"